- name: Extra repo for debian 
  apt_repository: repo='deb http://mirror.nl.leaseweb.net/debian/ jessie-backports main' state=present
  when: ansible_os_family == "Debian"

- name: Install packages 
  apt: name={{ item }} state={{ install_state }} update_cache=yes
  with_items: base_pkg
  when: ansible_os_family == "Debian" 
  
- name: Install the selinux python module
  yum: name=libselinux-python state=present
  when: ansible_os_family == "RedHat"

- name: Copy the epel packages 
  copy: src=epel.repo dest=/etc/yum.repos.d/epel_ansible.repo
  when: ansible_os_family == "RedHat"
  
- name: Install packages 
  yum: name={{item}} state={{ install_state }}
  with_items: base_pkg
  when: ansible_os_family == "RedHat"
